CREATE TABLE
	`university_db`.`Professor` (
		`SSN` INT NOT NULL,
		`F_NAME` VARCHAR(35) NOT NULL,
		`L_NAME` VARCHAR(35) NOT NULL,
		`STREET_ADDRESS` TEXT NOT NULL,
		`CITY` TEXT NOT NULL,
		`STATE` VARCHAR(25) NOT NULL,
		`ZIP` INT NOT NULL,
		`AREA_CODE` INT NOT NULL,
		`TELEPHONE` INT NOT NULL,
		`SEX` ENUM ('MALE', 'FEMALE', 'OTHER') NOT NULL,
		`TITLE` TEXT NOT NULL,
		`SALARY` INT NOT NULL,
		PRIMARY KEY (`SSN`)
	);

CREATE TABLE
	`university_db`.`Department` (
		`NUMBER` INT NOT NULL,
		`NAME` TEXT NOT NULL,
		`AREA_CODE` INT NOT NULL,
		`TELEPHONE` INT NOT NULL,
		`OFFICE_LOCATION` TEXT NOT NULL,
		`CHAIR_SSN` INT NOT NULL,
		PRIMARY KEY (`NUMBER`)
	);

ALTER TABLE `Department` ADD CONSTRAINT `fk_department_chair` FOREIGN KEY (`CHAIR_SSN`) REFERENCES `Professor` (`SSN`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Student` (
		`CWID` INT NOT NULL,
		`F_NAME` VARCHAR(35) NOT NULL,
		`L_NAME` VARCHAR(35) NOT NULL,
		`STREET_ADDRESS` TEXT NOT NULL,
		`CITY` TEXT NOT NULL,
		`STATE` VARCHAR(25) NOT NULL,
		`ZIP` INT NOT NULL,
		`MAJOR_DEPT_NO` INT NOT NULL,
		PRIMARY KEY (`CWID`)
	);

ALTER TABLE `Student` ADD CONSTRAINT `fk_student_majors` FOREIGN KEY (`MAJOR_DEPT_NO`) REFERENCES `Department` (`NUMBER`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Course` (
		`NUMBER` INT NOT NULL,
		`TITLE` TEXT NOT NULL,
		`UNITS` INT NOT NULL,
		`TEXTBOOK` TEXT NOT NULL,
		`DEPT_NO` INT NOT NULL,
		`PREREQUISITE` INT NOT NULL,
		PRIMARY KEY (`NUMBER`)
	);

ALTER TABLE `Course` ADD CONSTRAINT `fk_course_prerequisite` FOREIGN KEY (`PREREQUISITE`) REFERENCES `Course` (`NUMBER`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Section` (
		`COURSE_NO` INT NOT NULL,
		`NUMBER` INT NOT NULL,
		`CLASSROOM` VARCHAR(10) NOT NULL,
		`SEATS` INT NOT NULL,
		`BEGIN_TIME` TIME NOT NULL,
		`END_TIME` TIME NOT NULL,
		`PROFESSOR_SSN` INT NOT NULL,
		PRIMARY KEY (`COURSE_NO`, `NUMBER`)
	);

ALTER TABLE `Section` ADD CONSTRAINT `fk_section_instructor` FOREIGN KEY (`PROFESSOR_SSN`) REFERENCES `Professor` (`SSN`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Minor` (
		`CWID` INT NOT NULL,
		`DEPT_NO` INT NOT NULL,
		PRIMARY KEY (`CWID`, `DEPT_NO`)
	);

ALTER TABLE `Minor` ADD CONSTRAINT `fk_minor_student` FOREIGN KEY (`CWID`) REFERENCES `Student` (`CWID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Minor` ADD CONSTRAINT `fk_minor_dept` FOREIGN KEY (`DEPT_NO`) REFERENCES `Department` (`NUMBER`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Enrollment` (
		`CWID` INT NOT NULL,
		`COURSE_NO` INT NOT NULL,
		`SECTION_NO` INT NOT NULL,
		`GRADE` VARCHAR(2) NOT NULL,
		PRIMARY KEY (`CWID`, `COURSE_NO`, `SECTION_NO`)
	);

ALTER TABLE `Enrollment` ADD CONSTRAINT `fk_enrollment_student` FOREIGN KEY (`CWID`) REFERENCES `Student` (`CWID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Enrollment` ADD CONSTRAINT `fk_enrollment_course` FOREIGN KEY (`COURSE_NO`) REFERENCES `Section` (`COURSE_NO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE
	`university_db`.`Degree` (
		`PROFESSOR_SSN` INT NOT NULL,
		`DEGREE` VARCHAR(50) NOT NULL,
		PRIMARY KEY (`PROFESSOR_SSN`, `DEGREE`)
	);

CREATE TABLE
	`university_db`.`Meeting` (
		`SECTION_NO` INT NOT NULL,
		`DAY` VARCHAR(25) NOT NULL,
		PRIMARY KEY (`SECTION_NO`, `DAY`)
	);