CREATE TABLE
	`Professor` (
		`SSN` INT NOT NULL,
		`F_NAME` VARCHAR(35) NOT NULL,
		`L_NAME` VARCHAR(35) NOT NULL,
		`STREET_ADDRESS` TEXT NOT NULL,
		`CITY` TEXT NOT NULL,
		`STATE` VARCHAR(25) NOT NULL,
		`ZIP` INT NOT NULL,
		`AREA_CODE` INT NOT NULL,
		`TELEPHONE` INT NOT NULL,
		`SEX` ENUM ('MALE', 'FEMALE', 'OTHER') NOT NULL,
		`TITLE` TEXT NOT NULL,
		`SALARY` INT NOT NULL,
		PRIMARY KEY (`SSN`)
	);

CREATE TABLE
	`Department` (
		`NUMBER` INT NOT NULL,
		`NAME` TEXT NOT NULL,
		`AREA_CODE` INT NOT NULL,
		`TELEPHONE` INT NOT NULL,
		`OFFICE_LOCATION` TEXT NOT NULL,
		`CHAIR_SSN` INT NOT NULL,
		PRIMARY KEY (`NUMBER`),
		FOREIGN KEY (`CHAIR_SSN`) REFERENCES `Professor` (`SSN`)
	);

CREATE TABLE
	`Student` (
		`CWID` INT NOT NULL,
		`F_NAME` VARCHAR(35) NOT NULL,
		`L_NAME` VARCHAR(35) NOT NULL,
		`STREET_ADDRESS` TEXT NOT NULL,
		`CITY` TEXT NOT NULL,
		`STATE` VARCHAR(25) NOT NULL,
		`ZIP` INT NOT NULL,
		`MAJOR_DEPT_NO` INT NOT NULL,
		PRIMARY KEY (`CWID`),
		FOREIGN KEY (`MAJOR_DEPT_NO`) REFERENCES `Department` (`NUMBER`)
	);

CREATE TABLE
	`Course` (
		`NUMBER` INT NOT NULL,
		`TITLE` TEXT NOT NULL,
		`UNITS` INT NOT NULL,
		`TEXTBOOK` TEXT NOT NULL,
		`DEPT_NO` INT NOT NULL,
		PRIMARY KEY (`NUMBER`),
		FOREIGN KEY (`DEPT_NO`) REFERENCES `Department` (`NUMBER`)
	);

CREATE TABLE
	`Prerequisite` (
		`COURSE_NO` INT NOT NULL,
		`PREREQ_NO` INT NOT NULL,
		PRIMARY KEY (`COURSE_NO`, `PREREQ_NO`),
		FOREIGN KEY (`COURSE_NO`) REFERENCES Course (`NUMBER`),
		FOREIGN KEY (`PREREQ_NO`) REFERENCES Course (`NUMBER`)
	);

CREATE TABLE
	`Section` (
		`COURSE_NO` INT NOT NULL,
		`SECTION_NO` INT NOT NULL,
		`CLASSROOM` VARCHAR(10) NOT NULL,
		`SEATS` INT NOT NULL,
		`BEGIN_TIME` TIME NOT NULL,
		`END_TIME` TIME NOT NULL,
		`PROFESSOR_SSN` INT NOT NULL,
		PRIMARY KEY (`COURSE_NO`, `SECTION_NO`),
		FOREIGN KEY (`PROFESSOR_SSN`) REFERENCES `Professor` (`SSN`),
		FOREIGN KEY (`COURSE_NO`) REFERENCES `Course` (`NUMBER`)
	);

ALTER TABLE `Section` ADD INDEX (`SECTION_NO`);

CREATE TABLE
	`Minor` (
		`CWID` INT NOT NULL,
		`DEPT_NO` INT NOT NULL,
		PRIMARY KEY (`CWID`, `DEPT_NO`),
		FOREIGN KEY (`CWID`) REFERENCES `Student` (`CWID`),
		FOREIGN KEY (`DEPT_NO`) REFERENCES `Department` (`NUMBER`)
	);

CREATE TABLE
	`Enrollment` (
		`CWID` INT NOT NULL,
		`COURSE_NO` INT NOT NULL,
		`SECTION_NO` INT NOT NULL,
		`GRADE` VARCHAR(2) NOT NULL,
		PRIMARY KEY (`CWID`, `COURSE_NO`, `SECTION_NO`),
		FOREIGN KEY (`CWID`) REFERENCES `Student` (`CWID`),
		FOREIGN KEY (`COURSE_NO`) REFERENCES `Section` (`COURSE_NO`),
		FOREIGN KEY (`SECTION_NO`) REFERENCES `Section` (`SECTION_NO`)
	);

CREATE TABLE
	`Degree` (
		`PROFESSOR_SSN` INT NOT NULL,
		`DEGREE` VARCHAR(50) NOT NULL,
		PRIMARY KEY (`PROFESSOR_SSN`, `DEGREE`),
		FOREIGN KEY (`PROFESSOR_SSN`) REFERENCES `Professor` (`SSN`)
	);

CREATE TABLE
	`Meeting` (
		`SECTION_NO` INT NOT NULL,
		`DAY` VARCHAR(25) NOT NULL,
		PRIMARY KEY (`SECTION_NO`, `DAY`),
		FOREIGN KEY (`SECTION_NO`) REFERENCES `Section` (`SECTION_NO`)
	);